package de.bioforscher.singa.sequence.parser.ena;

import de.bioforscher.singa.features.identifiers.ENAAccessionNumber;
import de.bioforscher.singa.sequence.model.NucleotideSequence;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class ENAParserServiceTest {

    @Test
    public void shouldParseNucleotideSequence() {
        final NucleotideSequence sequence = ENAParserService.parse(new ENAAccessionNumber("CAA37856.1"));
        assertEquals("atgcgtacagaatattgtggacagctccgtttgtcccacgtggggcagcaggtgactctgtgtggttgggtcaaccgtcgtcgtgatcttggtagcctgatcttcatcgatatgcgcgaccgcgaaggtatcgtgcaggtatttttcgatccggatcgtgcggacgcgttaaagctggcctctgaactgcgtaatgagttctgcattcaggtcacgggcaccgtacgtgcgcgtgacgaaaaaaatattaaccgcgatatggcgaccggcgaaatcgaagtgctggcgtcctcgctgactatcatcaaccgcgcagatgttctgccgcttgactctaaccacgtcaacaccgaagaagcgcgtctgaaataccgctacctcgacctgcgtcgtccggaaatggctcagcgcctgaaaacccgcgctaaaatcaccagcctggtgcgccgttttatggatgaccacggcttcctcgacatcgaaactccgatgctgaccaaagccacgccggaaggcgcgcgtgactacctggtgccttctcgtgtgcacaaaggtaaattctacgcactgccgcaatccccgcagttgttcaaacagctgctgatgatgtccggttttgaccgttactatcagatcgttaaatgcttccgtgacgaagacctgcgtgctgaccgtcagcctgaatttactcagatcgatgtggaaacttctttcatgaccgcgccgcaagtgcgtgaagtgatggaagcgctggtgcgtcatctgtggctggaagtgaagggtgtggatctgggcgatttcccggtaatgacctttgcggaagcagaacgccgttatggttctgataaaccggatctgcgtaacccgatggaactgactgacgttgctgatctgctgaaatctgttgagtttgctgtatttgcaggtccggcgaacgatccgaaaggtcgcgtagcggctctgcgcgttccgggcggcgcatcgctgacccgtaagcagatcgacgaatacggtaacttcgttaaaatctacggcgcgaaaggtctggcttacatcaaagttaacgaacgcgcgaaaggtctggaaggtatcaacagcccggtagcgaagttccttaatgcagaaatcatcgaagacatcctggatcgtactgccgcgcaagatggcgatatgattttcttcggtgccgacaacaagaaaattgttgccgacgcgatgggtgcactgcgcctgaaagtgggtaaagaccttggtctgaccgacgaaagcaaatgggcaccgctgtgggttatcgacttcccgatgtttgaagacgacggtgaaggcggcctgacggcaatgcaccatccgttcacctcaccgaaagatatgacggctgcagaactgaaagctgcaccggaaaatgcggtggcgaacgcttacgatatggtcatcaatggttacgaagtgggcggtggttcagtacgtatccataatggtgatatgcagcagacggtgtttggtattctgggtatcaacgaagaggaacagcgcgagaaattcggcttcctgctcgacgctctgaaatacggtactccgccgcacgcaggtctggcattcggtcttgaccgtctgaccatgctgctgaccggcaccgacaatatccgtgacgttatcgccttcccgaaaaccacggcggcagcgtgtctgatgactgaagcaccgagctttgctaacccgactgcactggctgagctgagcattcaggttgtgaagaaggctgagaataactga",sequence.getSequenceAsString().toLowerCase());
        // assertEquals("MRTEYCGQLRLSHVGQQVTLCGWVNRRRDLGSLIFIDMRDREGIVQVFFDPDRADALKLASELRNEFCIQVTGTVRARDEKNINRDMATGEIEVLASSLTIINRADVLPLDSNHVNTEEARLKYRYLDLRRPEMAQRLKTRAKITSLVRRFMDDHGFLDIETPMLTKATPEGARDYLVPSRVHKGKFYALPQSPQLFKQLLMMSGFDRYYQIVKCFRDEDLRADRQPEFTQIDVETSFMTAPQVREVMEALVRHLWLEVKGVDLGDFPVMTFAEAERRYGSDKPDLRNPMELTDVADLLKSVEFAVFAGPANDPKGRVAALRVPGGASLTRKQIDEYGNFVKIYGAKGLAYIKVNERAKGLEGINSPVAKFLNAEIIEDILDRTAAQDGDMIFFGADNKKIVADAMGALRLKVGKDLGLTDESKWAPLWVIDFPMFEDDGEGGLTAMHHPFTSPKDMTAAELKAAPENAVANAYDMVINGYEVGGGSVRIHNGDMQQTVFGILGINEEEQREKFGFLLDALKYGTPPHAGLAFGLDRLTMLLTGTDNIRDVIAFPKTTAAACLMTEAPSFANPTALAELSIQVVKKAENN",sequence.getTranslationSequence());
        // assertEquals(11,sequence.getTranslationTable(),0);
    }

}